# Docker Compose override for development
# Use: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  backend:
    build:
      target: development
    environment:
      - ENVIRONMENT=development
      - GIN_MODE=debug
    volumes:
      - ./backend:/app
      - /app/tmp  # Exclude tmp directory from volume mount
    command: ["air", "-c", ".air.toml"]

  # Add pgAdmin for database management in development
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: helpdesk_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@helpdesk.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - helpdesk_network
    depends_on:
      - postgres
    profiles:
      - dev

volumes:
  pgadmin_data:
    driver: local
