name: helpdesk

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: helpdesk_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-helpdesk}
      POSTGRES_USER: ${POSTGRES_USER:-helpdesk_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-helpdesk_password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init/postgres:/docker-entrypoint-initdb.d
    networks:
      - helpdesk_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-helpdesk_user} -d ${POSTGRES_DB:-helpdesk}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: helpdesk_redis
    ports:
      - "${REDIS_PORT:-6380}:6379"  # External:Internal
    volumes:
      - redis_data:/data
    networks:
      - helpdesk_network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Mailhog for email testing (development only)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: helpdesk_mailhog
    ports:
      - "${MAILHOG_SMTP_PORT:-1025}:1025"  # SMTP port
      - "${MAILHOG_WEB_PORT:-8025}:8025"   # Web UI port
    networks:
      - helpdesk_network
    restart: unless-stopped
    profiles:
      - dev

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: helpdesk_backend
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    env_file:
      - ./backend/.env
    environment:
      # Override specific values for Docker environment
      - DATABASE_URL=postgres://${POSTGRES_USER:-helpdesk_user}:${POSTGRES_PASSWORD:-helpdesk_password}@postgres:5432/${POSTGRES_DB:-helpdesk}?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - SMTP_HOST=${SMTP_HOST:-mailhog}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - helpdesk_network
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/tmp  # Exclude tmp directory

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  helpdesk_network:
    driver: bridge
