root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/server"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "migrations"]
  exclude_regex = ["_test.go"]
  include_dir = ["."]
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "2s"
  rerun = true
  rerun_delay = 500
  send_interrupt = true
  poll = true
  poll_interval = 1000
[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
